# Stage 1: Build the Angular application
FROM node:16 AS build

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy application code
COPY . .

# Build the application
RUN npm run build --prod

# Stage 2: Serve the application
FROM nginx:alpine

# Copy built files from the build stage
COPY --from=build /app/dist/gestion-stagiares-front /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
